#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/common.sh"

output_file="$OUTPUT_DIR/a02-vendor.mk"
copyfile_list="$(mktemp)"
package_list="$(mktemp)"

find "$BLOB_DIR" -type f 2>/dev/null | sed "s#^$BLOB_DIR/##" | sort -u | while IFS= read -r rel; do
  case "$rel" in
    build.prop|default.prop|ro.prop|rw.prop) continue ;;
    *.so|*.apk|*.jar|*.xml|*.rc|*.json|*.bin|*.conf|*.ko|*.txt|*.sh|*.etc)
      printf '%s\n' "$rel" >> "$copyfile_list"
      ;;
  esac
done

find "$BLOB_DIR" -type f -name '*.so' 2>/dev/null | while IFS= read -r path; do
  rel_path="${path#"$BLOB_DIR"/}"
  base_name="$(basename "$rel_path")"
  module_name="lib$(printf '%s' "$base_name" | sed 's/\.so$//' | tr '.@/-' '_')"
  printf '%s\n' "$module_name" >> "$package_list"
  if file "$path" 2>/dev/null | grep -q 'ELF'; then
    :
  fi
done

{
  echo "# Auto-generated by generator."
  printf '%s\n' 'PRODUCT_COPY_FILES += \'
  copy_count="$(wc -l < "$copyfile_list")"
  idx=0
  while IFS= read -r rel; do
    idx=$((idx + 1))
    suffix=""
    if [ "$idx" -lt "$copy_count" ]; then
      suffix=' \\'
    fi
    printf '    vendor/%s/%s/proprietary/%s:vendor/%s%s\n' "$VENDOR_NAME" "$DEVICE_NAME" "$rel" "$rel" "$suffix"
  done < "$copyfile_list"
  echo ""
  printf '%s\n' 'PRODUCT_PACKAGES += \'
  pkg_count="$(wc -l < "$package_list")"
  idx=0
  while IFS= read -r pkg; do
    idx=$((idx + 1))
    suffix=""
    if [ "$idx" -lt "$pkg_count" ]; then
      suffix=' \\'
    fi
    printf '    %s%s\n' "$pkg" "$suffix"
  done < "$package_list"
} > "$output_file"

rm -f "$copyfile_list" "$package_list"
