#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/common.sh"

output_file="$OUTPUT_DIR/Android.bp"
module_file="$OUTPUT_DIR/.android-bp-modules.txt"
mkdir -p "$OUTPUT_DIR"

mktemp_list="$(mktemp)"
find "$BLOB_DIR" -type f -name '*.so' 2>/dev/null | while IFS= read -r path; do
  rel_path="${path#"$BLOB_DIR"/}"
  case "$rel_path" in
    firmware/*) continue ;;
    *.xml|*.rc|*.conf|*.json|*.bin|*.apk|*.jar|*.ko|*.txt) continue ;;
  esac
  if file "$path" 2>/dev/null | grep -q 'ELF'; then
    echo "$rel_path" >> "$mktemp_list"
  fi
done

if [ -s "$mktemp_list" ]; then
  sort -u "$mktemp_list" > "$module_file"
else
  : > "$module_file"
fi

{
  echo "// Auto-generated by generator."
  echo ""
  while IFS= read -r rel_path; do
    [ -n "$rel_path" ] || continue
    base_name="$(basename "$rel_path")"
    module_name="$(printf '%s' "$base_name" | sed 's/\.so$//' | tr '.@/-' '_')"
    module_name="lib${module_name}"
    echo "cc_prebuilt_library_shared {"
    echo "    name: \"${module_name}\","
    echo "    vendor: true,"
    echo "    compile_multilib: \"32\","
    echo "    stem: \"${base_name}\","
    echo "    srcs: [\"vendor/${VENDOR_NAME}/${DEVICE_NAME}/proprietary/${rel_path}\"],"
    echo "    shared_libs: [],"
    echo "    strip: {"
    echo "        none: true,"
    echo "    },"
    echo "}"
    echo ""
  done < "$module_file"
} > "$output_file"

rm -f "$mktemp_list"
