#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/common.sh"

mkdir -p "$OUTPUT_DIR"
output_file="$OUTPUT_DIR/proprietary-files.txt"

{
  echo "# Auto-generated by generator."
  echo "# Sorted unique relative paths only."
  find "$BLOB_DIR" -type f 2>/dev/null | sed "s#^$BLOB_DIR/##" | sort -u | while IFS= read -r rel; do
    case "$rel" in
      *.so|*.apk|*.jar|*.xml|*.rc|*.json|*.bin|*.conf|*.ko|*.etc|*.txt|*.sh)
        printf '%s\n' "$rel"
        ;;
    esac
  done
} > "$output_file"
